export const PROPERTY_INFO_LABELS = {
    REPORT_TITLE: 'Report Title',
    ADDRESS: 'Property Address',
    CITY: 'Property City',
    STATE: 'Property State',
    COMMUNITY: 'Property Community',
    COUNTY: 'Property County',
    ZIPCODE: 'ZIP Code',
    PROPERTY_TYPE: 'Property Type',
    ANNUAL_TAX: 'Annual Property Taxes',
    MLS_NUMBER: 'MLS Number',
    PHOTOS: 'Property Photos',
    DESCRIPTION: 'Property Description',
    BEDROOMS: 'Bedrooms',
    BATHROOMS: 'Bathrooms',
    TOTAL_SQFT: 'Total Sqft',
    LOT_SIZE: 'Lot Size (sqft)',
    YEAR_BUILT: 'Year Built',
    YEAR_RENOVATED: 'Year Renovated',
    UNITS: 'Units',
    STORIES: 'Stories',
    COUNTY_APPRAISED_VALUE: 'County Appraised Value',
    POOL: 'Pool',
    HEATING: 'Heating',
    COOLING: 'Cooling',
    FIREPLACE: 'Fireplace',
    GARAGE: 'Garage',
    CONSTRUCTION: 'Construction',
    ROOFING: 'Roofing',
    FLOORING_TYPES: 'Flooring Type(s)',
    WIRING_CONDITION: 'Wiring Condition',
    PLUMBING_CONDITION: 'Plumbing Condition',
    SIDING_MATERIAL: 'Siding Material',
    OTHER_INFORMATION: 'Other Information',
    LISTING_PRICE: 'Listing Price',
};
export const PURCHASE_LABELS = {
    PURCHASE_PRICE: 'Purchase Price',
    AFTER_REPAIR_VALUE: 'After Repair Value',
    CLOSING_COST: 'Purchase Closing Cost',
    PURCHASE_CLOSING_COST_BREAKDOWN: 'Purchase Closing Cost Breakdown',
    REPAIR_COST: 'Estimated Repair Cost',
    IS_CASH_PURCHASE: 'Is Cash Purchase',
    DOWN_PAYMENT: 'Down payment of purchase price',
    LOAN_INTEREST_RATE: 'Loan Interest Rate',
    POINTS_CHARGED_BY_LENDER: 'Points Charged By Lender',
    OTHER_CHARGES_FROM_THE_LENDER: 'Other Charges from the Lender',
    WRAP_LOAN_FEES_INTO_LOAN: 'Loan fees & points are wrapped into the loan',
    IS_INTEREST_ONLY: 'Is Interest Only',
    AMORTIZED_YEARS: 'Amortized Over How Many Years',
    TYPICAL_CAP_RATE: 'Typical Cap Rate for the Area',
};

export const RENTAL_LABELS = {
    MONTHLY_RENT: 'Total Gross Monthly Rent',
    OTHER_MONTHLY_INCOME: 'Other Monthly Income',
    ELECTRICITY: 'Electricity',
    WATER_AND_SEWER: 'Water & Sewer',
    PMI: 'PMI',
    GARBAGE: 'Garbage',
    HOA: 'HOAs',
    MONTHLY_INSURANCE: 'Monthly Insurance',
    OTHER_MONTHLY_EXPENSES: 'Other Monthly Expenses',
    VACANCY: 'Vacany',
    MAINTENANCE: 'Repairs and Maintenance',
    CAPEX: 'Capital Expenditures',
    MANAGEMENT_FEES: 'Management Fees',
    ANNUAL_INCOME_GROWTH: 'Annual Income Growth',
    ANNUAL_PV_GROWTH: 'Annual PV Growth',
    ANNUAL_EXPENSES_GROWTH: 'Annual Expenses Growth',
    SALES_EXPENSES: 'Sales Expenses',
};
export const PURCHASE_CLOSING_COST_BREAKDOWN_LABELS = {
    POINTS_FEE: 'Points Fee',
    PREPAID_HAZARD_INSURANCE: 'Prepaid Hazard Insurance',
    PREPAID_FLOOD_INSURANCE: 'Prepaid Flood Insurance',
    PREPAID_PROPERTY_TAXES: 'Prepaid Property Taxes',
    ANNUAL_ASSESSMENTS: 'Annual Assessments',
    TITLE_AND_ESCROW_FEES: 'Title and Escrow Fees',
    ATTORNEY_CHARGES: 'Attorney Charges',
    INSPECTION_COSTS: 'Inspection Costs',
    RECORDING_FEES: 'Recording Fees',
    APPRAISAL_FEES: 'Appraisal Fees',
    OTHER_FEES: 'Other Fees',
    TOTAL_SUM_PURCHASE: 'Total Sum Purchase',
};
export const REPAIR_COST_BREAKDOWN_LABELS = {
    ROOF: 'Roof',
    CONCRETE: 'Concrete',
    GUTTERS_SOFFIT_FASCIA: 'Gutters/Soffit/Fascia',
    GARAGE: 'Garage',
    SIDING: 'Siding',
    LANDSCAPING: 'Landscaping',
    EXTERIOR_PAINTING: 'Exterior Painting',
    SEPTIC: 'Septic',
    DECKS: 'Decks',
    FOUNDATION: 'Foundation',
    DEMO: 'Demo',
    SHEETROCK: 'Sheetrock',
    PLUMBING: 'Plumbing',
    CARPENTRY_WINDOW_DOORS: 'Carpentry/Windows/Doors',
    ELECTRICAL: 'Electrical',
    INTERIOR_PAINTING: 'Interior Painting',
    HVAC: 'HVAC',
    CABINETS_COUNTERTOPS: 'Cabinets/Countertops',
    FRAMING: 'Framing',
    FLOORING: 'Flooring',
    PERMITS: 'Permits',
    TERMITES: 'Termites',
    MOLD: 'Mold',
    MISCELLANEOUS: 'Miscellaneous',
    TOTAL_SUM_REPAIR: 'Total Sum Repai',
};
